apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dz4-chart.fullname" . }}-config
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  db_host: {{ .Values.app.config.database.host }}
  db_port: "{{ .Values.app.config.database.port }}"
  db_name: {{ .Values.app.config.database.name }}
  db_username: {{ .Values.app.config.database.user }}
